safe:           false
auto:           true
server:         yes
permalink:      /:title/

site_url:       'http://vstarkov.com'
site_rss:       '/atom.xml'
site_mail:      'hello@vstarkov.com'
site_name:      'Vladimir Starkov'
site_title:     'Vladimir Starkov; Tech Blog'

disqus_id:      'vstarkovcom'
g_analytics_id: 'UA-33247628-1'
g_verification: 'XodcflMjIifcToRCz8TgYAd2zySNqmAE6IKbqmqnd2o'

mirror_url:     'http://vstarkov.ru'
mirror_title:   'Читать на русском'

i18n_lang_code: 'en'
i18n_about:     'About'
i18n_rss:       'RSS'
i18n_close:     'Close'

i18n_january:   'January'
i18n_february:  'February'
i18n_march:     'March'
i18n_april:     'April'
i18n_may:       'May'
i18n_june:      'June'
i18n_july:      'July'
i18n_august:    'August'
i18n_september: 'September'
i18n_october:   'October'
i18n_november:  'November'
i18n_december:  'December'